namespace Core.Enem;

// These descriptions were extracted from the "Matriz de Referência" file
// Each one is related to a `HabilidadeId` by its index in the array 
public static class HabilidadesDescriptions
{
    public readonly static string[] CH = [
        "Interpretar historicamente e/ou geograficamente fontes documentais acerca de aspectos da cultura.",
        "Analisar a produção da memória pelas sociedades humanas.",
        "Associar as manifestações culturais do presente aos seus processos históricos.",
        "Comparar pontos de vista expressos em diferentes fontes sobre determinado aspecto da cultura.",
        "Identificar as manifestações ou representações da diversidade do patrimônio cultural e artístico em diferentes sociedades.",
        "Interpretar diferentes representações gráficas e cartográficas dos espaços geográficos.",
        "Identificar os significados histórico-geográficos das relações de poder entre as nações",
        "Analisar a ação dos estados nacionais no que se refere à dinâmica dos fluxos populacionais e no enfrentamento de problemas de ordem econômico-social.",
        "Comparar o significado histórico-geográfico das organizações políticas e socioeconômicas em escala local, regional ou mundial.",
        "Reconhecer a dinâmica da organização dos movimentos sociais e a importância da participação da coletividade na transformação da realidade histórico-geográfica.",
        "Identificar registros de práticas de grupos sociais no tempo e no espaço.",
        "Analisar o papel da justiça como instituição na organização das sociedades.",
        "Analisar a atuação dos movimentos sociais que contribuíram para mudanças ou rupturas em processos de disputa pelo poder.",
        "Comparar diferentes pontos de vista, presentes em textos analíticos e interpretativos, sobre situação ou fatos de natureza histórico-geográfica acerca das instituições sociais, políticas e econômicas.",
        "Avaliar criticamente conflitos culturais, sociais, políticos, econômicos ou ambientais ao longo da história.",
        "Identificar registros sobre o papel das técnicas e tecnologias na organização do trabalho e/ou da vida social.",
        "Analisar fatores que explicam o impacto das novas tecnologias no processo de territorialização da produção.",
        "Analisar diferentes processos de produção ou circulação de riquezas e suas implicações sócio-espaciais.",
        "Reconhecer as transformações técnicas e tecnológicas que determinam as várias formas de uso e apropriação dos espaços rural e urbano.",
        "Selecionar argumentos favoráveis ou contrários às modificações impostas pelas novas tecnologias à vida social e ao mundo do trabalho.",
        "Identificar o papel dos meios de comunicação na construção da vida social.",
        "Analisar as lutas sociais e conquistas obtidas no que se refere às mudanças nas legislações ou nas políticas públicas.",
        "Analisar a importância dos valores éticos na estruturação política das sociedades.",
        "Relacionar cidadania e democracia na organização das sociedades.",
        "Identificar estratégias que promovam formas de inclusão social.",
        "Identificar em fontes diversas o processo de ocupação dos meios físicos e as relações da vida humana com a paisagem.",
        "Analisar de maneira crítica as interações da sociedade com o meio físico, levando em consideração aspectos históricos e(ou) geográficos.",
        "Relacionar o uso das tecnologias com os impactos sócio-ambientais em diferentes contextos histórico-geográficos.",
        "Reconhecer a função dos recursos naturais na produção do espaço geográfico, relacionando-os com as mudanças provocadas pelas ações humanas.",
        "Avaliar as relações entre preservação e degradação da vida no planeta nas diferentes escalas.",
    ];

    public readonly static string[] CN = [
        "Reconhecer características ou propriedades de fenômenos ondulatórios ou oscilatórios, relacionando-os a seus usos em diferentes contextos.",
        "Associar a solução de problemas de comunicação, transporte, saúde ou outro, com o correspondente desenvolvimento científico e tecnológico.",
        "Confrontar interpretações científicas com interpretações baseadas no senso comum, ao longo do tempo ou em diferentes culturas.",
        "Avaliar propostas de intervenção no ambiente, considerando a qualidade da vida humana ou medidas de conservação, recuperação ou utilização sustentável da biodiversidade.",
        "Dimensionar circuitos ou dispositivos elétricos de uso cotidiano.",
        "Relacionar informações para compreender manuais de instalação ou utilização de aparelhos, ou sistemas tecnológicos de uso comum.",
        "Selecionar testes de controle, parâmetros ou critérios para a comparação de materiais e produtos, tendo em vista a defesa do consumidor, a saúde do trabalhador ou a qualidade de vida.",
        "Identificar etapas em processos de obtenção, transformação, utilização ou reciclagem de recursos naturais, energéticos ou matérias-primas, considerando processos biológicos, químicos ou físicos neles envolvidos.",
        "Compreender a importância dos ciclos biogeoquímicos ou do fluxo energia para a vida, ou da ação de agentes ou fenômenos que podem causar alterações nesses processos.",
        "Analisar perturbações ambientais, identificando fontes, transporte e(ou) destino dos poluentes ou prevendo efeitos em sistemas naturais, produtivos ou sociais.",
        "Reconhecer benefícios, limitações e aspectos éticos da biotecnologia, considerando estruturas e processos biológicos envolvidos em produtos biotecnológicos.",
        "Avaliar impactos em ambientes naturais decorrentes de atividades sociais ou econômicas, considerando interesses contraditórios.",
        "Reconhecer mecanismos de transmissão da vida, prevendo ou explicando a manifestação de características dos seres vivos.",
        "Identificar padrões em fenômenos e processos vitais dos organismos, como manutenção do equilíbrio interno, defesa, relações com o ambiente, sexualidade, entre outros.",
        "Interpretar modelos e experimentos para explicar fenômenos ou processos biológicos em qualquer nível de organização dos sistemas biológicos.",
        "Compreender o papel da evolução na produção de padrões, processos biológicos ou na organização taxonômica dos seres vivos.",
        "Relacionar informações apresentadas em diferentes formas de linguagem e representação usadas nas ciências físicas, químicas ou biológicas, como texto discursivo, gráficos, tabelas, relações matemáticas ou linguagem simbólica.",
        "Relacionar propriedades físicas, químicas ou biológicas de produtos, sistemas ou procedimentos tecnológicos às finalidades a que se destinam.",
        "Avaliar métodos, processos ou procedimentos das ciências naturais que contribuam para diagnosticar ou solucionar problemas de ordem social, econômica ou ambiental.",
        "Caracterizar causas ou efeitos dos movimentos de partículas, substâncias, objetos ou corpos celestes.",
        "Utilizar leis físicas e (ou) químicas para interpretar processos naturais ou tecnológicos inseridos no contexto da termodinâmica e(ou) do eletromagnetismo.",
        "Compreender fenômenos decorrentes da interação entre a radiação e a matéria em suas manifestações em processos naturais ou tecnológicos, ou em suas implicações biológicas, sociais, econômicas ou ambientais.",
        "Avaliar possibilidades de geração, uso ou transformação de energia em ambientes específicos, considerando implicações éticas, ambientais, sociais e/ou econômicas.",
        "Utilizar códigos e nomenclatura da química para caracterizar materiais, substâncias ou transformações químicas.",
        "Caracterizar materiais ou substâncias, identificando etapas, rendimentos ou implicações biológicas, sociais, econômicas ou ambientais de sua obtenção ou produção.",
        "Avaliar implicações sociais, ambientais e/ou econômicas na produção ou no consumo de recursos energéticos ou minerais, identificando transformações químicas ou de energia envolvidas nesses processos.",
        "Avaliar propostas de intervenção no meio ambiente aplicando conhecimentos químicos, observando riscos ou benefícios.",
    ];

    public readonly static string[] LC = [
        "Identificar as diferentes linguagens e seus recursos expressivos como elementos de caracterização dos sistemas de comunicação.",
        "Recorrer aos conhecimentos sobre as linguagens dos sistemas de comunicação e informação para resolver problemas sociais.",
        "Relacionar informações geradas nos sistemas de comunicação e informação, considerando a função social desses sistemas.",
        "Reconhecer posições críticas aos usos sociais que são feitos das linguagens e dos sistemas de comunicação e informação." ,
        "Associar vocábulos e expressões de um texto em LEM ao seu tema.",
        "Utilizar os conhecimentos da LEM e de seus mecanismos como meio de ampliar as possibilidades de acesso a informações, tecnologias e culturas.",
        "Relacionar um texto em LEM, as estruturas linguísticas, sua função e seu uso social.",
        "Reconhecer a importância da produção cultural em LEM como representação da diversidade cultural e linguística.",
        "Reconhecer as manifestações corporais de movimento como originárias de necessidades cotidianas de um grupo social.",
        "Reconhecer a necessidade de transformação de hábitos corporais em função das necessidades cinestésicas.",
        "Reconhecer a linguagem corporal como meio de interação social, considerando os limites de desempenho e as alternativas de adaptação para diferentes indivíduos.",
        "Reconhecer diferentes funções da arte, do trabalho da produção dos artistas em seus meios culturais.",
        "Analisar as diversas produções artísticas como meio de explicar diferentes culturas, padrões de beleza e preconceitos.",
        "Reconhecer o valor da diversidade artística e das inter-relações de elementos que se apresentam nas manifestações de vários grupos sociais e étnicos.",
        "Estabelecer relações entre o texto literário e o momento de sua produção, situando aspectos do contexto histórico, social e político.",
        "Relacionar informações sobre concepções artísticas e procedimentos de construção do texto literário.",
        "Reconhecer a presença de valores sociais e humanos atualizáveis e permanentes no patrimônio literário nacional.",
        "Identificar os elementos que concorrem para a progressão temática e para a organização e estruturação de textos de diferentes gêneros e tipos.",
        "Analisar a função da linguagem predominante nos textos em situações específicas de interlocução.",
        "Reconhecer a importância do patrimônio linguístico para a preservação da memória e da identidade nacional.",
        "Reconhecer em textos de diferentes gêneros, recursos verbais e não-verbais utilizados com a finalidade de criar e mudar comportamentos e hábitos.",
        "Relacionar, em diferentes textos, opiniões, temas, assuntos e recursos linguísticos.",
        "Inferir em um texto quais são os objetivos de seu produtor e quem é seu público alvo, pela análise dos procedimentos argumentativos utilizados.",
        "Reconhecer no texto estratégias argumentativas empregadas para o convencimento do público, tais como a intimidação, sedução, comoção, chantagem, entre outras.",
        "Identificar, em textos de diferentes gêneros, as marcas linguísticas que singularizam as variedades linguísticas sociais, regionais e de registro.",
        "Relacionar as variedades linguísticas a situações específicas de uso social.",
        "Reconhecer os usos da norma padrão da língua portuguesa nas diferentes situações de comunicação.",
        "Reconhecer a função e o impacto social das diferentes tecnologias da comunicação e informação.",
        "Identificar pela análise de suas linguagens, as tecnologias da comunicação e informação.",
        "Relacionar as tecnologias de comunicação e informação ao desenvolvimento das sociedades e ao conhecimento que elas produzem.",
    ];

    public readonly static string[] MT = [
        "Reconhecer, no contexto social, diferentes significados e representações dos números e operações - naturais, inteiros, racionais ou reais.",
        "Identificar padrões numéricos ou princípios de contagem.",
        "Resolver situação-problema envolvendo conhecimentos numéricos.",
        "Avaliar a razoabilidade de um resultado numérico na construção de argumentos sobre afirmações quantitativas.",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos numéricos.",
        "Interpretar a localização e a movimentação de pessoas/objetos no espaço tridimensional e sua representação no espaço bidimensional.",
        "Identificar características de figuras planas ou espaciais.",
        "Resolver situação-problema que envolva conhecimentos geométricos de espaço e forma.",
        "Utilizar conhecimentos geométricos de espaço e forma na seleção de argumentos propostos como solução de problemas do cotidiano.",
        "Identificar relações entre grandezas e unidades de medida.",
        "Utilizar a noção de escalas na leitura de representação de situação do cotidiano.",
        "Resolver situação-problema que envolva medidas de grandezas.",
        "Avaliar o resultado de uma medição na construção de um argumento consistente.",
        "Avaliar proposta de intervenção na realidade utilizando conhecimentos geométricos relacionados a grandezas e medidas.",
        "Identificar a relação de dependência entre grandezas.",
        "Resolver situação-problema envolvendo a variação de grandezas, direta ou inversamente proporcionais.",
        "Analisar informações envolvendo a variação de grandezas como recurso para a construção de argumentação.",
        "Avaliar propostas de intervenção na realidade envolvendo variação de grandezas.",
        "Identificar representações algébricas que expressem a relação entre grandezas.",
        "Interpretar gráfico cartesiano que represente relações entre grandezas.",
        "Resolver situação-problema cuja modelagem envolva conhecimentos algébricos.",
        "Utilizar conhecimentos algébricos/geométricos como recurso para a construção de argumentação.",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos algébricos.",
        "Utilizar informações expressas em gráficos ou tabelas para fazer inferências.",
        "Resolver problema com dados apresentados em tabelas ou gráficos.",
        "Analisar informações expressas em gráficos ou tabelas como recurso para a construção de argumentos.",
        "Calcular medidas de tendência central ou de dispersão de um conjunto de dados expressos em uma tabela de frequências de dados agrupados (não em classes) ou em gráficos.",
        "Resolver situação-problema que envolva conhecimentos de estatística e probabilidade.",
        "Utilizar conhecimentos de estatística e probabilidade como recurso para a construção de argumentação.",
        "Avaliar propostas de intervenção na realidade utilizando conhecimentos de estatística e probabilidade.",
    ];
}