include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_positional_boolean_parameters: false
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    camel_case_types: true
    cancel_subscriptions: true
    curly_braces_in_flow_control_structures: true
    file_names: true
    lines_longer_than_80_chars: false
    parameter_assignments: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_mixin: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    sort_pub_dependencies: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_this: false
    valid_regexps: true
    constant_identifier_names: false
    depend_on_referenced_packages: false
    prefer_interpolation_to_compose_strings: false
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: false
    sort_child_properties_last: false
    use_build_context_synchronously: false
    require_trailing_commas: true
