name: microdados_enem_app
description: "A new Flutter project."
publish_to: "none"

version: 1.1.3

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.0.0
  flutter_hooks: 0.21.2
  http: ^1.3.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - prod.env
    - dev.env
    - assets/onboarding/

  fonts:
    - family: Rawline
      fonts:
        - asset: assets/fonts/rawline-100.ttf
          weight: 100
        - asset: assets/fonts/rawline-200.ttf
          weight: 200
        - asset: assets/fonts/rawline-300.ttf
          weight: 300
        - asset: assets/fonts/rawline-400.ttf
          weight: 400
        - asset: assets/fonts/rawline-500.ttf
          weight: 500
        - asset: assets/fonts/rawline-600.ttf
          weight: 600
        - asset: assets/fonts/rawline-700.ttf
          weight: 700
        - asset: assets/fonts/rawline-800.ttf
          weight: 800
        - asset: assets/fonts/rawline-900.ttf
          weight: 900
        - asset: assets/fonts/rawline-100i.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/rawline-200i.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/rawline-300i.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/rawline-400i.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/rawline-500i.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/rawline-600i.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/rawline-700i.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/rawline-800i.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/rawline-900i.ttf
          style: italic
          weight: 900
